leftnav:
- identifier: 7a8d320a-5e59-7606-259f-e859bc5c7ff1
  name: Syllabus
  pageRef: /courses/21w-732-5-introduction-to-technical-communication-explorations-in-scientific-and-technical-writing-fall-2006/sections/syllabus
  weight: 10
- identifier: 44eabdb4-193c-1f9b-a98d-bcf8a3805d60
  name: Calendar
  pageRef: /courses/21w-732-5-introduction-to-technical-communication-explorations-in-scientific-and-technical-writing-fall-2006/sections/calendar
  weight: 20
- identifier: 1111f5ea-e54a-800e-aafb-d454f7d43f99
  name: Readings
  pageRef: /courses/21w-732-5-introduction-to-technical-communication-explorations-in-scientific-and-technical-writing-fall-2006/sections/readings
  weight: 30
- identifier: b0cd2206-1cc5-993b-11f4-1ac290f73287
  name: Assignments
  pageRef: /courses/21w-732-5-introduction-to-technical-communication-explorations-in-scientific-and-technical-writing-fall-2006/sections/assignments
  weight: 40
- identifier: ad7ce4ac-efe6-afb2-9e6f-4c3e286c260c
  name: Related Resources
  pageRef: /courses/21w-732-5-introduction-to-technical-communication-explorations-in-scientific-and-technical-writing-fall-2006/sections/related-resources
  weight: 50
